server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      start-saga: start-saga
      orquestrator: orquestrator
      finish-success: finish-success
      finish-fail: finish-fail
    consumer:
      group-id: order-group
      auto-offset-reset: latest

# Desligar log do kafka
logging:
  level:
    org:
      apache:
        kafka: OFF