#
# conectar via bash 'sudo docker exec -it product-service-database psql -U postgres'
#

version: '3'

services:

  #
  # KAFKA
  #
  kafka:
    container_name: kafka
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - orchestrator-saga
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    volumes:
      - ./data/kafka/data:/var/lib/kafka/data

  #
  # Redpanda
  #
  redpanda-console:
    container_name: redpanda
    image: docker.redpanda.com/redpandadata/console:v2.3.8
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    ports:
      - "8081:8080"
    networks:
      - orchestrator-saga
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:29092"]
    depends_on:
      - "kafka"

  #
  # Order service database
  #
  order-service-db:
    image: mongo:latest
    container_name: order-service-database
    restart: always
    networks:
      - orchestrator-saga
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"

  #
  # Product service database
  #
  product-service-db:
    image: postgres:latest
    container_name: product-service-database
    networks:
      - orchestrator-saga
    environment:
      - POSTGRES_DB=product-database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5431:5432"

  #
  # Payment service database
  #
  payment-service-db:
    image: postgres:latest
    container_name: payment-service-database
    networks:
      - orchestrator-saga
    environment:
      - POSTGRES_DB=payment-database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"

  #
  # Inventory service databse
  #
  inventory-service-db:
    image: postgres:latest
    container_name: inventory-service-database
    networks:
      - orchestrator-saga
    environment:
      - POSTGRES_DB=inventory-database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"

  #
  # Order service application
  #
  order-service:
    build: './order-service'
    container_name: order-service
    depends_on:
      - order-service-db
      - kafka
    networks:
      - orchestrator-saga
    environment:
      - KAFKA_BROKER=kafka:29092
      - MONGO_DB_URI=mongodb://admin:123456@order-service-db:27017
    ports:
      - "3000:3000"

  product-service:
    build: './product-service'
    container_name: product-service
    depends_on:
      - product-service-db
      - kafka
    networks:
      - orchestrator-saga
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=product-service-db
      - DB_NAME=product-database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8090:8090"

  payment-service:
    build: './payment-service'
    container_name: payment-service
    depends_on:
      - payment-service-db
      - kafka
    networks:
      - orchestrator-saga
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=payment-service-db
      - DB_NAME=payment-database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8091:8091"

  inventory-service:
    build: './inventory-service'
    container_name: inventory-service
    depends_on:
      - inventory-service-db
      - kafka
    networks:
      - orchestrator-saga
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=inventory-service-db
      - DB_NAME=inventory-database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8092:8092"

  orquestrator-service:
    build: './orquestry-service'
    container_name: orquestry-service
    depends_on:
      - kafka
    networks:
      - orchestrator-saga
    environment:
      - KAFKA_BROKER=kafka:29092
    ports:
      - "8080:8080"

networks:
  orchestrator-saga:
    driver: bridge