server:
  port: 8091

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:payment-database}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      # Para deletar o banco toda vez que descer a aplicacao
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      orquestrator: orquestrator
      payment-success: payment-success
      payment-fail: payment-fail
    consumer:
      group-id: product-group
      auto-offset-reset: latest

    # Desligar log do kafka
logging:
  level:
    org:
      apache:
        kafka: OFF