server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5431}/${DB_NAME:product-database}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        # For√ßa o Hibernate a cuspir qualquer erro de schema no log
        hbm2ddl.auto: create

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      # ORCHESTRATOR TOPIC
      orchestrator: orchestrator
      # PROCUCT SUCCESS TOPIC
      product-success: product-success
      # PROCUCT FAIL TOPIC
      product-fail: product-fail

    consumer:
      group-id: product-group
      auto-offset-reset: latest

  # Desligar log do kafka
logging:
  level:
    org:
      apache:
        kafka: OFF